= ISO ICS codes (edition 7) in machine-processible formats

== General

ISO International Classification for Standards (ICS) codes are used
amongst international standards for categorization purposes
especially in ISO and IEC standards.

== Purpose

While ISO provides them in a PDF form for public usage, they are
not available in machine-readable form.

The contents of this repository aims to provide ICS codes in
machine-readable form (JSON and JSON-LD).


== Models

=== ICS code

ICS codes are made up of one to three code sections.

* The first code section represents the "`field`" (the "`field code`")
* The second is optional, represents the "`group`" (the "`group code`")
* The third is optional, represents the "`subgroup`" (the "`subgroup code`")

[example]
.ICS code entry
====
`03.100.30` has field code `03`, group code `100`, and subgroup code `30`.
====


=== ICS code data

An ICS code represents a data structure that contains:

* Field code (mandatory)
* Group code (optional)
* Subgroup code (optional)
* Description (mandatory)
* Notes (optional), there can be multiple notes.

[source,json]
----
{
  "code": "03.100.30",
  "fieldcode": "03",
  "description": "Management of human resources",
  "groupcode": "100",
  "subgroupcode": "30",
  "@context": "https://isoics.org/ics/ns/subgroup.jsonld",
  "descriptionFull": "Services. Company organization, management and quality."
                     "Administration. Transport. Sociology. Company organization"
                     "and management. Management systems. Management of human"
                     "resources.",
  "notes": [
    "..."
  ]
}
----

=== ICS note

Each ICS note contains:

* A textual portion
* One or more links to other ICS codes. The position of the linked code is given within the textual portion

Example without link:

[source,json]
----
{
  "text": "Including staff training, staff responsibilities,"
          "staff qualifications and certification"
}
----

Example with link:

[source,json]
----
{
  "text": "Welding, brazing and soldering in general, see {ics-code}",
  "ics-code": "25.160.01"
}
----


== JSON ICS

This is an example of an ICS entry in this repository.

https://github.com/metanorma/iso-ics-codes/blob/master/ics/03_100_30.json

[source,json]
----
{
  "code": "03.100.30",
  "fieldcode": "03",
  "description": "Management of human resources",
  "groupcode": "100",
  "subgroupcode": "30",
  "@context": "https://isoics.org/ics/ns/subgroup.jsonld",
  "descriptionFull": "Services. Company organization, management and quality. Administration. Transport. Sociology. Company organization and management. Management systems. Management of human resources.",
  "notes": [
    {
      "text": "Including staff training, staff responsibilities, staff qualifications and certification"
    },
    {
      "text": "Welding, brazing and soldering in general, see {ics-code}",
      "ics-code": "25.160.01"
    }
  ]
}
----

* In an ICS subgroup, the JSON representation provides you with both the description of the subgroup and of the group.
* Notice it also contains a JSONLD context (which is not yet resolvable).


== Usage

Files are directly named using the ICS codes in order to enable machine
access for the data related to every single ICS code.

For clarity, the "`fullstop`" symbol is replaced with an underscore in
a filename.

For example,

* `01.json` contains data of ICS code `01` (field code `01`)
* `01_020.json` contains data of ICS code `01.020` (field code `01`, group code `020`)
* `01_040_01.json` contains data of ICS code `01.040.01` (field code `01`, group code `040`, subgroup code `01`)


== Data source

The data source is the 2015 edition of ISO ICS, which are also available
from the ISO
https://www.iso.org/standards-catalogue/browse-by-ics.html["`Browse by ICS`"]
interface.

These files are created by using scripts located in
https://github.com/metanorma/iso-ics-codes-scripts[`iso-ics-codes-scripts`].



== Credits

This code list is maintained by the https://www.metanorma.org[Ribose Metanorma project].

== License

The code here is available under the terms of the
http://opensource.org/licenses/MIT[MIT License].

