name: build

on:
  push:
    branches:
    - main
    tags: [ v* ]
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup yq
        uses: frenck/action-setup-yq@v1

      - name: Verify that YAML files are normalized
        run: make check-normalized

      - name: Check JSON files can be generated
        run: make json-all
