name: build

on:
  push:
    branches:
    - main
    tags: [ v* ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup yq
        uses: frenck/action-setup-yq@v1

      - name: Verify that YAML files are normalized
        run: make check-normalized

      - name: Check JSON files can be generated
        run: make json-all

      - name: Generate release deliverables
        run: make release

      - uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: ics
          path: |
            ics-ed6-yaml.zip
            ics-ed6-json.zip
            ics-ed6.yaml
            ics-ed6.json
            ics-ed7-yaml.zip
            ics-ed7-json.zip
            ics-ed7.yaml
            ics-ed7.json
          retention-days: 1

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: ics

      - name: Display structure of downloaded files
        run: ls -R

      - name: Get Version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

      - name: Rename artifact
        run: |
          mv ics-ed6-yaml.zip ics-ed6-yaml-${{ steps.get_version.outputs.VERSION }}.zip
          mv ics-ed6-json.zip ics-ed6-json-${{ steps.get_version.outputs.VERSION }}.zip
          mv ics-ed6.yaml ics-ed6-${{ steps.get_version.outputs.VERSION }}.yaml
          mv ics-ed6.json ics-ed6-${{ steps.get_version.outputs.VERSION }}.json
          mv ics-ed7-yaml.zip ics-ed7-yaml-${{ steps.get_version.outputs.VERSION }}.zip
          mv ics-ed7-json.zip ics-ed7-json-${{ steps.get_version.outputs.VERSION }}.zip
          mv ics-ed7.yaml ics-ed7-${{ steps.get_version.outputs.VERSION }}.yaml
          mv ics-ed7.json ics-ed7-${{ steps.get_version.outputs.VERSION }}.json

      - name: Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          body: Automatic release of ${{ github.ref }}
          files: |
            ics-ed6-*
            ics-ed7-*
